NumPy

In [1]:
import numpy as np

In [2]:
#1d array

In [3]:
myarr=np.array([3,6,27,7])

In [4]:
myarr

array([ 3,  6, 27,  7])

In [7]:
myarr=np.array([3,6,27,7],np.int8)

In [8]:
myarr

array([ 3,  6, 27,  7], dtype=int8)

In [12]:
myarr=np.array([3,6,276551515265155151,7],np.int64)

In [13]:
myarr=np.array([3,6,27,7],np.int8)

In [14]:
myarr

array([ 3,  6, 27,  7], dtype=int8)

In [15]:
myarr[2]

27

In [16]:
myarr[1]

6

In [17]:
myarr[3]=50

In [18]:
myarr

array([ 3,  6, 27, 50], dtype=int8)

In [19]:
myarr.shape

(4,)

In [20]:
myarr.dtype

dtype('int8')

In [21]:
myarr.ndim

1

In [22]:
a=['shahsish',24,69,52]

In [23]:
b=np.array(a)

In [24]:
b

array(['shahsish', '24', '69', '52'], dtype='<U8')

array creation methods in numpy

In [34]:
listarray=np.array([[2,3,1],[8,5,7],[6,8,4]])

In [35]:
listarray

array([[2, 3, 1],
       [8, 5, 7],
       [6, 8, 4]])

In [36]:
listarray.shape

(3, 3)

In [37]:
listarray.size

9

In [38]:
listarray.ndim

2

In [39]:
zero=np.zeros((4,3))

In [40]:
zero

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [41]:
zero.dtype

dtype('float64')

In [42]:
zero.shape

(4, 3)

In [43]:
one=np.ones((5,5))

In [44]:
one

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [45]:
rng=np.arange(15)

In [46]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [47]:
rng=np.arange(5,20,3)

In [48]:
rng

array([ 5,  8, 11, 14, 17])

In [51]:
linsp=np.linspace(1,15)#evenly spaced elements default=50

In [52]:
linsp

array([ 1.        ,  1.28571429,  1.57142857,  1.85714286,  2.14285714,
        2.42857143,  2.71428571,  3.        ,  3.28571429,  3.57142857,
        3.85714286,  4.14285714,  4.42857143,  4.71428571,  5.        ,
        5.28571429,  5.57142857,  5.85714286,  6.14285714,  6.42857143,
        6.71428571,  7.        ,  7.28571429,  7.57142857,  7.85714286,
        8.14285714,  8.42857143,  8.71428571,  9.        ,  9.28571429,
        9.57142857,  9.85714286, 10.14285714, 10.42857143, 10.71428571,
       11.        , 11.28571429, 11.57142857, 11.85714286, 12.14285714,
       12.42857143, 12.71428571, 13.        , 13.28571429, 13.57142857,
       13.85714286, 14.14285714, 14.42857143, 14.71428571, 15.        ])

In [53]:
linsp=np.linspace(1,15,8)

In [54]:
linsp

array([ 1.,  3.,  5.,  7.,  9., 11., 13., 15.])

In [55]:
linsp.size

8

In [56]:
emp=np.empty((4,6))

In [57]:
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        2.33646845e-307, 1.33511018e-306, 1.33511969e-306],
       [6.23037996e-307, 6.23053954e-307, 9.34609790e-307,
        8.45593934e-307, 9.34600963e-307, 9.34603000e-307],
       [9.34593493e-307, 1.86920872e-306, 6.23054972e-307,
        1.42419530e-306, 8.90098127e-307, 8.01106038e-307],
       [8.45603441e-307, 6.23059726e-307, 8.45602762e-307,
        1.33511969e-306, 2.22522596e-306, 1.42410974e-306]])

In [58]:
emp[1][3]=5213

In [59]:
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        2.33646845e-307, 1.33511018e-306, 1.33511969e-306],
       [6.23037996e-307, 6.23053954e-307, 9.34609790e-307,
        5.21300000e+003, 9.34600963e-307, 9.34603000e-307],
       [9.34593493e-307, 1.86920872e-306, 6.23054972e-307,
        1.42419530e-306, 8.90098127e-307, 8.01106038e-307],
       [8.45603441e-307, 6.23059726e-307, 8.45602762e-307,
        1.33511969e-306, 2.22522596e-306, 1.42410974e-306]])

In [61]:
emp_like=np.empty_like(zero)

In [62]:
emp_like

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [65]:
ide=np.identity(3)

In [66]:
ide

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [67]:
ide.shape

(3, 3)

In [68]:
a=np.arange(99)

In [69]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [70]:
a.ndim

1

In [71]:
a.shape

(99,)

In [74]:
a.reshape(3,33)#only shows

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [75]:
a.reshape(33,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29],
       [30, 31, 32],
       [33, 34, 35],
       [36, 37, 38],
       [39, 40, 41],
       [42, 43, 44],
       [45, 46, 47],
       [48, 49, 50],
       [51, 52, 53],
       [54, 55, 56],
       [57, 58, 59],
       [60, 61, 62],
       [63, 64, 65],
       [66, 67, 68],
       [69, 70, 71],
       [72, 73, 74],
       [75, 76, 77],
       [78, 79, 80],
       [81, 82, 83],
       [84, 85, 86],
       [87, 88, 89],
       [90, 91, 92],
       [93, 94, 95],
       [96, 97, 98]])

In [76]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [77]:
a=a.reshape(3,33)

In [78]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [79]:
a.ravel()#local change

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [81]:
a=a.ravel()

In [82]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [83]:
a.reshape(11,9)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59, 60, 61, 62],
       [63, 64, 65, 66, 67, 68, 69, 70, 71],
       [72, 73, 74, 75, 76, 77, 78, 79, 80],
       [81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98]])

In [84]:
a=a.reshape(11,9)

In [85]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59, 60, 61, 62],
       [63, 64, 65, 66, 67, 68, 69, 70, 71],
       [72, 73, 74, 75, 76, 77, 78, 79, 80],
       [81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98]])

In [86]:
a.ndim

2

In [87]:
a.size

99

In [88]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59, 60, 61, 62],
       [63, 64, 65, 66, 67, 68, 69, 70, 71],
       [72, 73, 74, 75, 76, 77, 78, 79, 80],
       [81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98]])

In [89]:
a[3:7,3:8]

array([[30, 31, 32, 33, 34],
       [39, 40, 41, 42, 43],
       [48, 49, 50, 51, 52],
       [57, 58, 59, 60, 61]])

In [90]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59, 60, 61, 62],
       [63, 64, 65, 66, 67, 68, 69, 70, 71],
       [72, 73, 74, 75, 76, 77, 78, 79, 80],
       [81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98]])

In [93]:
a[5:8,0:9]

array([[45, 46, 47, 48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59, 60, 61, 62],
       [63, 64, 65, 66, 67, 68, 69, 70, 71]])

In [94]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59, 60, 61, 62],
       [63, 64, 65, 66, 67, 68, 69, 70, 71],
       [72, 73, 74, 75, 76, 77, 78, 79, 80],
       [81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98]])

In [95]:
a.sum()

4851

In [97]:
a.sum(axis=0)

array([495, 506, 517, 528, 539, 550, 561, 572, 583])

In [98]:
a.sum(axis=1)

array([ 36, 117, 198, 279, 360, 441, 522, 603, 684, 765, 846])

In [99]:
a=np.array([[2,3,1],[8,5,7],[6,8,4]])

In [100]:
a

array([[2, 3, 1],
       [8, 5, 7],
       [6, 8, 4]])

In [101]:
a.sum()

44

In [102]:
a.sum(axis=0)

array([16, 16, 12])

In [103]:
a.sum(axis=1)

array([ 6, 20, 18])

In [104]:
a

array([[2, 3, 1],
       [8, 5, 7],
       [6, 8, 4]])

In [105]:
a.T

array([[2, 8, 6],
       [3, 5, 8],
       [1, 7, 4]])

In [106]:
a.flat

In [107]:
for i in a.flat:
    print(i)

2
3
1
8
5
7
6
8
4


In [108]:
a.ndim

2

In [110]:
a.nbytes#total bytes consumed

36

In [111]:
a

array([[2, 3, 1],
       [8, 5, 7],
       [6, 8, 4]])

In [116]:
b=np.array([12,52,20,14,85,74,96,3,1,100])

In [117]:
b.argmax()#index od max element

9

In [118]:
b.argmin()

8

In [120]:
b.argsort()#sorts the array and returns on the basis of index

array([8, 7, 0, 3, 2, 1, 5, 4, 6, 9], dtype=int64)

In [121]:
a

array([[2, 3, 1],
       [8, 5, 7],
       [6, 8, 4]])

In [122]:
a.argmin()

2

In [123]:
a.argmax()

3

In [124]:
a.argmin(axis=0)

array([0, 0, 0], dtype=int64)

In [126]:
a.argmin(axis=1)

array([2, 1, 2], dtype=int64)

In [127]:
a.argmax(axis=0)

array([1, 2, 1], dtype=int64)

In [128]:
a

array([[2, 3, 1],
       [8, 5, 7],
       [6, 8, 4]])

In [129]:
a.argmax(axis=1)

array([1, 0, 1], dtype=int64)

In [130]:
a.argsort(axis=0)

array([[0, 0, 0],
       [2, 1, 2],
       [1, 2, 1]], dtype=int64)

In [131]:
a.argsort(axis=1)

array([[2, 0, 1],
       [1, 2, 0],
       [2, 0, 1]], dtype=int64)

In [132]:
a

array([[2, 3, 1],
       [8, 5, 7],
       [6, 8, 4]])

In [133]:
a.ravel()

array([2, 3, 1, 8, 5, 7, 6, 8, 4])

In [134]:
a.reshape(9,1)

array([[2],
       [3],
       [1],
       [8],
       [5],
       [7],
       [6],
       [8],
       [4]])

In [135]:
a.reshape(1,9)

array([[2, 3, 1, 8, 5, 7, 6, 8, 4]])

In [136]:
a

array([[2, 3, 1],
       [8, 5, 7],
       [6, 8, 4]])

In [137]:
b=np.arange(9).reshape(3,3)

In [138]:
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [139]:
a+b

array([[ 2,  4,  3],
       [11,  9, 12],
       [12, 15, 12]])

In [140]:
a,b,a+b

(array([[2, 3, 1],
        [8, 5, 7],
        [6, 8, 4]]),
 array([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]),
 array([[ 2,  4,  3],
        [11,  9, 12],
        [12, 15, 12]]))

In [141]:
a*b

array([[ 0,  3,  2],
       [24, 20, 35],
       [36, 56, 32]])

In [142]:
a

array([[2, 3, 1],
       [8, 5, 7],
       [6, 8, 4]])

In [143]:
np.sqrt(a)

array([[1.41421356, 1.73205081, 1.        ],
       [2.82842712, 2.23606798, 2.64575131],
       [2.44948974, 2.82842712, 2.        ]])

In [144]:
a

array([[2, 3, 1],
       [8, 5, 7],
       [6, 8, 4]])

In [145]:
np.where(a>5)

(array([1, 1, 2, 2], dtype=int64), array([0, 2, 0, 1], dtype=int64))

In [148]:
np.where(a>6)

(array([1, 1, 2], dtype=int64), array([0, 2, 1], dtype=int64))

In [149]:
np.count_nonzero(a)

9

In [150]:
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [151]:
np.count_nonzero(b)

8

In [152]:
np.nonzero(b)

(array([0, 0, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))

In [153]:
import sys

In [154]:
py_ar=[0,4,55,2]

In [155]:
np_ar=np.array(py_ar)

In [156]:
py_ar,np_ar

([0, 4, 55, 2], array([ 0,  4, 55,  2]))

In [157]:
sys.getsizeof(1)*len(py_ar)

112

In [159]:
np_ar.itemsize*np_ar.size

16

In [160]:
a

array([[2, 3, 1],
       [8, 5, 7],
       [6, 8, 4]])

In [161]:
a.itemsize

4

In [162]:
a.size

9

In [163]:
a.itemsize*a.size

36